### ISSUE TITLE
failure due to Utp endpoint InvalidPacket

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/crust#285] opened 2015-08-28 16:33 UTC
Env: 12 droplets (including 6 hard coded endpoints) and 1 droplet running the `safe_client` `self_authentication` example - receiving the warning below: 

```
safe@SAFE-ROUTING-9:~/safe_client/target/release/examples$ RUST_LOG=debug ./self_authentication 

Do you already have an account created (enter Y for yes) ?
Y


	Manual Account Login
	====================

------------ Enter Keyword ---------------
Fraser


------------ Enter Password --------------
tictac


--------- Enter PIN (4 Digits) -----------
0999

Trying to log in ...
WARN:crust::transport: NOTE: Transport connect 178.62.7.96:5483 failure due to Utp endpoint InvalidPacket
WARN:crust::transport: NOTE: Transport connect 37.59.98.1:5483 failure due to Utp endpoint InvalidPacket
WARN:crust::transport: NOTE: Transport connect 45.55.207.180:5483 failure due to Utp endpoint InvalidPacket
WARN:crust::transport: NOTE: Transport connect 45.79.93.11:5483 failure due to Utp endpoint InvalidPacket
WARN:crust::transport: NOTE: Transport connect 128.199.199.210:5483 failure due to Utp endpoint InvalidPacket
WARN:crust::transport: NOTE: Transport connect 45.79.2.52:5483 failure due to Utp endpoint InvalidPacket
```

**Comment by vinipsmaker** [comment] 2015-09-15 10:37
Hi @rossmuir , crust suffered a lot of internal changes since this bug was issued. I tried to reproduce it (using less nodes than you), but I haven't see any warning related to `InvalidPacket` and `Utp`. Could you check if this bug is still happening?

**Comment by rossmuir** [comment] 2015-09-16 14:24
Sure I can retest - thanks

**Comment by vinipsmaker** [comment] 2015-09-17 11:15
A theory: Beacon used UDP and the same port as uTP, then `InvalidPacket`s were read.

Beacon is using a different port now: https://github.com/maidsafe/crust/commit/7b3c9cf2ca9caeea8a733cc3b74153c883f9f78b#diff-0fb07a438eb34eab8647cbaa5b5a7482R41

**Comment by vinipsmaker** [comment] 2015-09-17 11:17
A theory: Beacon used UDP and the same port as uTP, then `InvalidPacket`s were read.

Beacon is using a different port now: https://github.com/maidsafe/crust/commit/7b3c9cf2ca9caeea8a733cc3b74153c883f9f78b#diff-0fb07a438eb34eab8647cbaa5b5a7482R41

**Comment by vinipsmaker** [comment] 2015-09-17 11:21
Closing the issue as I cannot reproduce it.

**Closed by vinipsmaker** 2015-09-17 11:21 UTC
