### ISSUE TITLE
expected_peers check doesn't work.

### ISSUE THREAD

**Issue by afck** [maidsafe/crust#615] opened 2016-03-18 16:47 UTC
In fact, we currently don't see any `NewPeer` events at all in Routing, and it looks like the new peer ID is not put in the `expected_peers` map in `Service::connect` at all.
Also, Crust needs to be able to make the connection even if there are a few seconds between the calls to `connect` from the two sides, so the acceptor needs to wait before either responding with a `CrustMsg::Connect` or cancelling the connection.

**Comment by madadam** [comment] 2016-03-21 09:12
I start wondering whether https://github.com/maidsafe/crust/pull/608 was actually the right thing to do. Since `connect` handles both direct and rendezvous connections, maybe the requirement to fire `NewPeer` only after both parties call `connect` should apply only to rendezvous connections and not direct connections?

Also, the `expected_peers` map wasn't really used before #608 (as far as I could tell). Now it's used to make sure `NewPeer` is not raised incorrectly, but maybe this is not what it was intended for?

**Comment by afck** [comment] 2016-03-24 08:23
I'm pretty sure that map was introduced for this purpose (although the implementation wasn't finished), and we do want that behaviour, even for direct connections: It's a lot easier for routing that way. The problem is that it needs to map the peer ID it gets in `NewPeer` to the public ID of the node it wants to connect to, and it can only do that once it at least has the peer's connection info.

**Comment by madadam** [comment] 2016-03-30 12:15
Can you verify this issue is still present? I believe it was caused by TCP rendezvous connection being temporarily disabled, but it's been enabled again in master.

**Comment by afck** [comment] 2016-04-01 07:19
The first part is fixed, but we shouldn't cancel the connection in https://github.com/maidsafe/crust/blob/master/src/connection.rs#L534. Instead, we would need to wait for a while here, in case `Service::connect` is called and the expected peer added.

I think this will be necessary for cases where A is behind a bad Router, so B can't directly connect to A, but A can directly connect to B. If A calls `connect` first, B would currently reject the connection, and later fail to establish it itself.

**Comment by ustulation** [comment] 2016-06-18 14:46
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.

**Closed by ustulation** 2016-06-18 14:46 UTC
