### ISSUE TITLE
Improve initial dashboard loading performance time by adding local storage

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/crust#1059] opened 2018-10-26 12:04 UTC

**Comment by nadiaburborough** [comment] 2018-10-29 10:46
Previous logs totalled about 9k logs. Run a test for 20k in production to benchmark performance.

**Comment by S-Coyle** [comment] 2018-10-29 16:16
To use as a benchmark for when this has been applied, here are some test notes of current performance:

**Test aim** - check performance with 20,000 unique (as per dashboard) entries displaying on the dashboard, in production. This is before local storage solution has been applied, and so will allow us to compare subsequent refreshes, after local storage has been applied.
**Details** - The number in the db doesn't equate to the number displayed on the dashboard because results flagged as {"isHairpinned" : true} are filtered out, therefore my actual test data for the initial loading test below is as follows:
Total db entries = **21216** (db.connectionlogs.count())
Db entries where {"isHairpinned" : true} = **1223** (db.connectionlogs.count({"isHairpinned" : true}))
Dashboard "Total Connection Attempts" = **19993** (confirmed that this matches expected number, i.e. 21216-1223 = 19993)
Performance results loading the dashboard for the 1st time with the above numbers:
- Chrome = 20 secs
- FF = 26 secs - though for Nadia this took 53 seconds
- Safari = 19 secs

Note that these results seem to vary depending on the users bandwidth, and some other factors.

**Comment by S-Coyle** [comment] 2018-10-30 15:26
Received message from Srini and Krishna advising that this is ready to be deployed - moving to Ready For QA column

**Comment by S-Coyle** [comment] 2018-10-30 16:10
After improvement:
- Chrome 1st load = 23 secs
- Chrome 2nd load = 17 secs
- FF 1st load = 23 secs
- FF 2nd load = 18 secs
- Safari 1st load = 15 secs
- Safari 2nd load = 13 secs

Looks good! Will run an office test to see if there are any knock on negative effects

**Closed by S-Coyle** 2018-10-30 16:10 UTC
Labels: Front End, enhancement
