### ISSUE TITLE
Newly added test_network_utp hogs CPU and fails to finish

### ISSUE THREAD

**Issue by inetic** [maidsafe/crust#412] opened 2015-11-09 13:15 UTC
The test is currently here https://github.com/inetic/crust/tree/utp-network , I'll soon create a PR to add it into master (with #[ignored] for now), because CIs currently seem to fail for other reasons.

The test creates N nodes and exchanges K messages between them, if TCP sockets are used (test_network_tcp) then everything is OK, but when uTP is used, some connections are created and some messages exchanged, but then the test seems to freeze with CPU being used on 100%.

My theory is that there is a bug in the congestion control algorithm in rust-utp, so I'll now be working on creating a similar test against rust-utp itself to prove or disprove this theory.

**Comment by inetic** [comment] 2015-11-09 19:36
Update: I created a test that creates a small local network [here](https://github.com/inetic/rust-utp/tree/test_network). The test fails, but a lot less often than our crust/utp-network test, suggesting there is a problem in both libraries.

When the rust-utp/test_network test is run the statistics I see are approximately as follows:
node count: 10; message count: 4: no failure
node count: 30; message count: 4: fails once in 5 runs
node count: 60; message count: 4: fails once in ~4 runs

**Comment by inetic** [comment] 2015-11-10 09:36
The example I created above is slightly different to our usage and I now believe that is the reason it fails a lot less often. In the example the per node algorithm goes something like this:

```
n times do
    write
    read
```

While in Crust we make use of the [timeout functionality we introduced](https://github.com/maidsafe/rust-utp/commit/6b6dd56c3ca2606c75fa66a71983478c04370dad), and the algorithm goes someting like this:

```
until (n reads) and (n writes)
    if less than n writes: write
    if less than n reads: read-with-timeout
```

If I modify the `test_network` example in `rust-utp` to use the timeouts, I can also reproduce the CPU hogging there. Suggesting the timeout implementation is not correct.

**Comment by vinipsmaker** [comment] 2015-11-10 20:04
> because CIs currently seem to fail for other reasons

now it's failing for the expected reasons: https://ci.appveyor.com/project/MaidSafe-QA/crust/build/1.0.395

**Comment by inetic** [comment] 2015-11-10 20:59
>> because CIs currently seem to fail for other reasons

> now it's failing for the expected reasons: https://ci.appveyor.com/project/MaidSafe-QA/crust/build/1.0.395

Nope, that seems like yet again different reason. Expected would have been (at time of writing the "because CIs currently...") that the test `test_network_utp` would fail. But since that comment, I made one fix [here](https://github.com/maidsafe/rust-utp/commit/2addaf44addd45c61d2d0827d0e9b7f0a63d031c) and it has been put into crate already (version 0.6.18).

The failure you linked to @vinipsmaker seems like is unrelated, but it is hard to tell since we've been [merging failing PRs](https://github.com/maidsafe/crust/pulls?q=is%3Apr+is%3Aclosed) into master recently :-(

Today I was working on the network tests in rust-utp ([here](https://github.com/inetic/rust-utp/blob/c5759d5c0234a50b14311caa3278f5a8d85d736d/src/socket.rs#L2812) and [here](https://github.com/inetic/rust-utp/blob/c5759d5c0234a50b14311caa3278f5a8d85d736d/src/socket.rs#L2841)). As I mentioned yesterday, the one not using timeouts sometimes failed and the one which used timeouts failed much more often with CPU running on 100%. I found one bug which I [fixed](https://github.com/inetic/rust-utp/commit/4832f19a1e79214fd3641b25ba2a89b2f689a6b7) and now both versions of the test fail only rarely and it also seems to have fixed the CPU hogging.

**Comment by inetic** [comment] 2015-11-11 16:09
Today I was mostly looking into Crust (not rust-utp), I tried running the `crust_peer` example with debug output on different droplets (network of size 20). Many instances worked flawlessly, and had established connections to all other nodes they were supposed to. But there were few which did not connect to all the other nodes. I traced the problem to the `rust-utp/UtpSocket::connect(...)` function where the error returned was `SocketError::InvalidPacket`, I think this suggest the rust-utp library has problem connecting over an unreliable link.

So I switched my focus back to `rust-utp` but this time with the `netem` on linux which (among other things ) helps emulate dropped packets. With this I was able to reproduce similar errors I saw on droplets so that is what I'll be working on next.

If someone wants to try it, here is how:

```
sudo tc qdisc add dev lo root netem loss 0.01%
cd <rust-utp>
cargo test test_network_no_timeout -- --nocapture
sudo tcp qdisc del dev lo root
```

(tomorrow I'll create simpler test than the network one)

**Comment by vinipsmaker** [comment] 2015-11-20 07:42
> Today I was working on the network tests in rust-utp ([here](https://github.com/inetic/rust-utp/blob/c5759d5c0234a50b14311caa3278f5a8d85d736d/src/socket.rs#L2812) and [here](https://github.com/inetic/rust-utp/blob/c5759d5c0234a50b14311caa3278f5a8d85d736d/src/socket.rs#L2841)). As I mentioned yesterday, the one not using timeouts sometimes failed and the one which used timeouts failed much more often with CPU running on 100%. I found one bug which I [fixed](https://github.com/inetic/rust-utp/commit/4832f19a1e79214fd3641b25ba2a89b2f689a6b7) and now both versions of the test fail only rarely and it also seems to have fixed the CPU hogging.

Commit https://github.com/inetic/rust-utp/commit/4832f19a1e79214fd3641b25ba2a89b2f689a6b7 makes a lot of tests from rust-utp fail. Reading Rust documentation [we can spot that a 0-bytes read is used to signalize EOF](http://doc.rust-lang.org/nightly/std/io/trait.Read.html#tymethod.read), so it's most likely the error is on the rust-utp usage and not on rust-utp itself.

I did the following `TcpStream` test, which is the interface that rust-utp is most likely trying to mirror:

```rust
#[test]
fn vinipsmaker() {
    use std::net::{TcpStream, Shutdown};
    let mut stream = TcpStream::connect("127.0.0.1:8080").unwrap();

    stream.shutdown(Shutdown::Both);

    println!("{:?}", stream.read(&mut [0; 128]));
    println!("{:?}", stream.read(&mut [0; 128]));
}
```

And the output was:

```
running 1 test
Ok(0)
Ok(0)
test vinipsmaker ... ok
```

Therefore, an `Err` result is not the proper way to notify `EOF` and we should (1) revert [this commit](https://github.com/inetic/rust-utp/commit/4832f19a1e79214fd3641b25ba2a89b2f689a6b7) and (2) implement the solution elsewhere.

**Comment by vinipsmaker** [comment] 2015-11-20 07:45
Regardless the bug we're hunting, upstream rust-utp has a bugfix for another bug and we should pull [this commit](https://github.com/meqif/rust-utp/commit/0edb5cac3e2c7eb1bf22a63a6c522b652c727f24) later.

**Comment by vinipsmaker** [comment] 2015-11-20 08:29
> Therefore, an `Err` result is not the proper way to notify `EOF` and we should (1) revert [this commit](https://github.com/inetic/rust-utp/commit/4832f19a1e79214fd3641b25ba2a89b2f689a6b7) and (2) implement the solution elsewhere.

I submitted a [PR to fix this issue on crust side](https://github.com/maidsafe/crust/pull/429) and now I'll check if the CPU hog still happens. [This commit](https://github.com/inetic/rust-utp/commit/4832f19a1e79214fd3641b25ba2a89b2f689a6b7) was also reverted.

I verified the CPU hogging doesn't happen anymore. But as before, fixing this issue don't prevent the test to fail sometimes.

**Comment by vinipsmaker** [comment] 2015-11-20 17:03
I've collected some stats running the `test_network_no_timeout` test from `test_network` branch a few times.

 ok | err | hang
--- | --- | ----
 25 |  10  |  14

The "hang" column is very subjective, as I've considered a run as hunged anytime I got bored waiting (likely a time between 10s and 30s, but I didn't really measured my boring-ness). Anyway, I think we should run the test at least 45 times and no error should be raised from the `rust-utp/UtpSocket::connect(...)` call when we make any patch to rust-utp in a attempt to fix the error. So, as this error doesn't happen every time, this is the test to check if we fixed it, run the test 45 times and check no errors were raised.

**Comment by dirvine** [comment] 2015-11-20 17:37
I am not sure it's all possible but being able to run with `rr` (debugger) would allow replay when the hang happens?

**Comment by vinipsmaker** [comment] 2015-11-20 17:40
> I am not sure it's all possible but being able to run with `rr` (debugger) would allow replay when the hang happens?

I believe it'd. I remember trying before. But the problem is that the `rust-gdb` is quite annoying compared to `gdb` being used for C++ projects. I'd like to have a backtrace that isn't hidden all over macros that don't give line information when debugging Rust code.

**Comment by dirvine** [comment] 2015-11-20 17:42
Yes not easy, like debugging c++ templates in many ways. It would be interesting to see how this waterfall happens for rust as they seem focussed on ide integration which I assume will mean looking more at debugging. If anyone knows a way to tame macros when debugging then great.

**Comment by maqi** [comment] 2015-11-27 09:06
After the rust-utp PR https://github.com/maidsafe/rust-utp/pull/8 merged, the crust service::test::test_network_utp test seems experiencing no hanging issue and doesn't see a failure either.
However, the time of completing the test is quite different, ranging from less than 5 seconds to over 30 seconds.

**Comment by maqi** [comment] 2015-11-27 12:56
Regarding the hanging issue for service::test::test_network_utp, it is actually because of missing messages.
The PR https://github.com/maidsafe/crust/pull/437 has changed the testing code little bit so missing message won't cause the test hanging (but will still fail the test)

**Comment by vinipsmaker** [comment] 2015-11-27 21:31
## Wrap-up of today's investigation

I worked on top of the https://github.com/maqi/crust/tree/test_network_utp branch.

Tests would only pass if I removed [this code](https://github.com/maqi/crust/blob/3c845098cdac9e8e2009ef080c035377c4e77507/src/service.rs#L744-L747). There would be a small chance (usually 1 out of 23) that the test would hang. I added some code to measure the hang cause and traced the problem to be non-received messages.

Adding a `sleep` between "this node is okay" and `drop(service)` didn't change hanging rate significantly, so it's unlikely that there is a race here preventing scheduled messages to be sent back.

I'm still investigating why there are messages that weren't sent back.

**Comment by maqi** [comment] 2015-12-02 10:21
## Summary of the works so far

This hanging issue turns out to be composed of two issues : 
1, The failing of utp connection establishment and missing of exchanged msg
According to the work of Rust-UTP PR https://github.com/maidsafe/rust-utp/pull/8 , the test proves a failing rate at around : 0.005% when socket without timeout and 0.25% when socket with timeout.
However, according to the work of Crust PR https://github.com/maidsafe/crust/pull/437 , the test proves the crust level failing rate is around the same as the rust-utp when socket with timeout.
The previous testing code expects a 100% success and will HANG when not reach it. The updated testing code in the above two PRs will complete the test in case of failure happens. 
Crust Issue https://github.com/maidsafe/crust/issues/439 has been raised separately for this part.

2, The crust CI builds on Windows will HANG after all tests get passed and completed.
This seems a long existing and shall be the original purpose of this issue being raised.
It has to be highlighted that even the service::test::test_network_utp has been logged as OK in the building log, the CI build still hangs as a whole on Windows OS (never seen it happen in Linux builds).
The test on rust-utp lib doesn't see such behaviour.
Will still use this issue as the main thread of the debugging work.

**Comment by vinipsmaker** [comment] 2015-12-02 19:13
> 2, The crust CI builds on Windows will HANG after all tests get passed and completed.

It "smells" like a leaking thread problem. I'll focus on issue `#1` (#439). Good luck.

**Comment by vinipsmaker** [comment] 2015-12-28 21:43
> I verified the CPU hogging doesn't happen anymore.

  -- https://github.com/maidsafe/crust/issues/412#issuecomment-158321389

This issue was originally created to track the CPU hogging issue, but this issue has been fixed already.

> 1, The failing of utp connection establishment and missing of exchanged msg
> 2, The crust CI builds on Windows will HANG after all tests get passed and completed.

  -- https://github.com/maidsafe/crust/issues/412#issuecomment-161249183

- `#1` (#439) has been fixed already.
- `#2` has a separate issue now: https://github.com/maidsafe/crust/issues/455

Gonna close this issue.

**Closed by vinipsmaker** 2015-12-28 21:43 UTC
