### ISSUE TITLE
Possible self-bootstrapping

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/crust#388] opened 2015-10-30 10:15 UTC
As discovered by debugging the routing connection management an intermittent failure (perhaps related to the bootstrap cache file, but a unvalidated guess), occurs for crust 0.4.2, where a single node can bootstrap to itself.

@vinipsmaker 's test does not showcase this issue (so far), which might indicate some bootstrap cache file residue causing it?
```
 #[test]
    fn examine_self_bootstrapping() {
        let (tx, rx) = ::std::sync::mpsc::channel();
        let mut service = ::crust::Service::new(tx).unwrap();
        service.bootstrap();
        let timeout = ::time::Duration::seconds(5);
        let start = ::time::now();
        let mut result = Err(::std::sync::mpsc::TryRecvError::Empty);
        while ::time::now() < start + timeout && result.is_err() {
            result = rx.try_recv();
            if let Ok(ref ev) = result {
                match *ev {
                    ::crust::Event::OnAccept(ref ep) => {
                        panic!("What the hell? {:?}", ep);
                    },
                    _ => {
                        panic!("aaa {:?}", *ev);
                    },
                }
            }
            ::std::thread::sleep_ms(100);
        }
    }
```

**Comment by benjaminbollen** [comment] 2015-10-30 10:22
Yesterdays observations (repeated from issue https://github.com/maidsafe/routing/issues/757) were eg :

```
$ RUST_LOG=routing=debug ./target/release/examples/key_value_store --node
INFO:routing::routing_node: RoutingNode Client(e61f88..ed1119) listens on [Tcp(V4(127.0.0.1:5483)), Tcp(V4(192.168.0.3:5483))]
DEBUG:routing::routing: Started routing run().
DEBUG:routing::routing_node: RoutingNode started running and started bootstrap
DEBUG:routing::routing_node: handle_on_connect: Disconnected adding unknown bootstrap Connection(Tcp V4(127.0.0.1:55474) -> V4(127.0.0.1:5483))
DEBUG:routing::routing_core: add_unknown_bootstrap_connection: added Connection(Tcp V4(127.0.0.1:55474) -> V4(127.0.0.1:5483))
DEBUG:routing::routing_core: add_unknown_bootstrap_connection: set state Bootstrapped
DEBUG:routing::routing_node: Saying hello I am Client(e61f88..ed1119) on Connection(Tcp V4(127.0.0.1:55474) -> V4(127.0.0.1:5483)), confirming None
DEBUG:routing::routing_node: handle_on_accept: Bootstrapped so not accepting Connection(Tcp V4(127.0.0.1:5483) -> V4(127.0.0.1:55474)). Dropping
DEBUG:routing::routing_node: Hello, it is Client(e61f88..ed1119) on Connection(Tcp V4(127.0.0.1:5483) -> V4(127.0.0.1:55474))
ERROR:routing::routing_core: Failed to add client Client(e61f88..ed1119) as relay connection on Connection(Tcp V4(127.0.0.1:5483) -> V4(127.0.0.1:55474)). Dropping.
DEBUG:routing::routing_node: Lost connection on Connection(Tcp V4(127.0.0.1:55474) -> V4(127.0.0.1:5483))
```

**Comment by inetic** [comment] 2015-11-02 10:15
I've been thinking about this, but if my theory is correct, there may not be much we can do about this from Crust. Here is one problematic scenario:

--------------------------
We have on PC starting two nodes, one listens on endpoint X, the other one on port 5483. The one listening on 5483 adds X to it's bootstrap list. Then, another time, another node is created and it starts listening on X.port(), it looks into the bootstrap list where X is as well, then it tries to connect to itself. If X was stored in the bootstrap list as 127.0.0.1:PortX, then we could filter it out, but X could be stored in the bootstrap list using an external IP address in which case we wouldn't be able to do much about it (without a per service UUID)

**Comment by vinipsmaker** [comment] 2015-11-03 07:27
I reproduced this bug under the `master` branch (and saved the state using the @dirvine's suggested `rr` tool). Unfortunately, my test case had a `panic!` under the `BootstrapFinished` event and I don't know if some event would follow. And the `rust-gdb` interface isn't helping me much in exploring the environment. Anyway, I noticed a weird `utp` endpoint in the bootstrap cache even thou `"utp_listening_port"` attribute is set to `null` under the config file of the runned test.

I improved the test example and while it was running I've been examining bootstrap sequence in crust to try to find the issue.

If you have any hint (the environment you use) to increase the change of hitting the issue, it'd be helpful.

**Comment by vinipsmaker** [comment] 2015-11-04 06:44
I thought there was a difference in behaviour between MAC and Linux, but I just realized that I wasn't observing the same behaviour in Linux because there was not enough time (the bootstrap cache list was giant). I assumed the difference in behaviour to be a bug in bootstrap and as the original bug, but it's not.

**Comment by vinipsmaker** [comment] 2015-11-04 06:46
@benjaminbollen, can you provide your config and cache files for after a failing run?

**Comment by inetic** [comment] 2015-11-04 11:27
So on today's meeting we discussed this, and it came up again that this is most likely because the bootstrap cache file contains an endpoint which points to the address we're currently listening on. As a workaround @benjaminbollen suggested that we wouldn't add any loopback addresses nor addresses from our local LAN to the bootstrap cache. This makes sense as we can always find such addresses using beacon and more often than not they would be obsolete very soon.

**Comment by vinipsmaker** [comment] 2015-11-04 15:30
> As a workaround @benjaminbollen suggested that we wouldn't add any loopback addresses nor addresses from our local LAN to the bootstrap cache.

Even if this is a "workaround", I think it should be done anyway. Gonna code the proposed solution.

> This makes sense as we can always find such addresses using beacon and more often than not they would be obsolete very soon.

Makes sense.

**Comment by vinipsmaker** [comment] 2015-11-09 09:45
Closing this issue now that #402 got merged. Reopen if needed.

**Closed by vinipsmaker** 2015-11-09 09:45 UTC
