### ISSUE TITLE
Default config file/cache file path needs to be current_exe_path

### ISSUE THREAD

**Issue by chandraprakash** [maidsafe/crust#196] opened 2015-07-20 13:10 UTC
Default config file/cache file path needs to be current_exe_path.
This also need to be documented in sync with installer.

**Comment by Fraser999** [comment] 2015-07-20 14:56
Duplicate of https://github.com/maidsafe/crust/issues/193

Please add any comments to that issue.

**Closed by Fraser999** 2015-07-20 14:56 UTC
