### ISSUE TITLE
Listen on Port can not be created properly sometime, and connection establishment is sometime router dependent

### ISSUE THREAD

**Issue by maqi** [maidsafe/crust#337] opened 2015-09-22 13:04 UTC
when vault network tests to be executed, a log from routing is like this `INFO:routing::routing_node: RoutingNode Client(9e7117..9fecfd) listens on [Tcp(V4(192.168.1.80:5483))]` . However, if a safe_vault executable being run, log from routing is like `INFO:routing::routing_node: RoutingNode Client(534c41..e78617) listens on []`, and the executable tests will be failed, as no connection can be established among nodes.

When run with MaidSafe-2G network, routing of first node can start listen on 5483, but the second node can not connect to it, according to the log (https://slack-files.com/T02KSMR3M-F0AU3BTUP-303a251f26), it seems the hyper lib having issue with fetching and closing the connection.
when run with MaidSafe-ADSL wireless, connection among nodes can be established, and logs from hyper indication a proper exchange of msg (https://slack-files.com/T02KSMR3M-F0AU51ZUY-f7695ea4f6)
However, on my machine, even when run with MaidSafe-ADSL, executing safe_vault or the executable_test (calling safe_vault executable directly) can not start routing listening on any port:
```
INFO:routing::routing_node: RoutingNode Client(32c9f7..e74a47) listens on []
```
and there is no log from hyper, indicates a disable of hyper for safe_vault executable.

**Comment by vinipsmaker** [comment] 2015-09-22 23:16
looks like there is no UPnP port mapping on the MaidSafe-2G network. Maybe this is a case where hole punching will help a lot. Also, the fact that the MaidSafe-ADSL works is a sign that UPnP port mapping implementation works and is helping crust to establish connections on more networks.

**Comment by vinipsmaker** [comment] 2015-09-22 23:21
I'll investigating more on the:

    INFO:routing::routing_node: RoutingNode Client(32c9f7..e74a47) listens on []

**Comment by vinipsmaker** [comment] 2015-09-22 23:22
Can you give me steps on how to reproduce the steps (including a commit id from safe_vault that shows the problem)?

**Comment by maqi** [comment] 2015-09-23 08:23
the "listens on []" issue exists with the current head of vault's master branch, you can take this as a reference (https://github.com/maidsafe/safe_vault/commit/ba26063ecac35c29f9d4aa47592b4b2f7d95ea20).
It is easy to reproduce: just build and run safe_vault .
However it seems quite machine dependent: on my machine, I can observe the issue always (with/without wireless/cabled network). But on Fraser's machine, it has never been observed.

And, needs to mention that I don't see this issue couple of month ago.
safe_vault works fine on my machine before the routing and crust got refactored.

**Comment by vinipsmaker** [comment] 2015-09-23 09:24
> However it seems quite machine dependent

In that case, which operating system show this problem?

**Comment by maqi** [comment] 2015-09-23 14:08
My machine is on ubuntu 14.04 LTS.
Fraser's machine is on ubuntu 15.04.
Droplets used for networking test also using 15.04 and seems don't have this issue reported.

**Comment by inetic** [comment] 2015-10-01 11:13
@maqi Crust shall start listening on ports which are listed in the config file (the `tcp_listening_port` and `utp_listening_port` values). Shaving a config file where these values are not set might be one source of the problem. Another could be that there already is an application bound to 5483 port on your PC, pls check `netstat` for that. Previously when Crust read the config file and there was no value, it started to listen on 5483 anyway, this behavior is only valid for MaidSafe and since Crust it expected to be general purpose, it was removed.

> When run with MaidSafe-2G network, routing of first node can start listen on 5483, but the second node can not connect to it

Yes, most mobile operators provide no UPnP functionality and are behind a Symmetric-NATs, so even if we implement UDP hole punching in this sprint, until we have port prediction in place we won't be able to connect to such nodes (even with port prediction we will not connect 100% of all cases, we'll just increase our chances).

**Comment by inetic** [comment] 2015-10-30 09:18
So, to summarize, I think this is the expected behavior. As there has not been any activity, I'm going to close this one. Please reopen if you think I'm wrong.

**Closed by inetic** 2015-10-30 09:18 UTC
Labels: bug
