### ISSUE TITLE
Cannot compile. Stuck at `Building [==>]168/172: rust_sodium-sys(build)`

### ISSUE THREAD

**Issue by czyczk** [maidsafe/crust#1125] opened 2019-02-18 13:03 UTC
**OS:**
Windows 10 1809

**Rust:**
stable-msvc / stable-gnu 2019-01-16

**Problem:**

After running `cargo build` or `cargo run --example crust_peer`, it gets stuck at

Building [====================================================>  ] 165/169: rust_sodium-sys(build)

After terminating the compilation, one of the following 3 situations might occur:

**1.** Get stuck again at rust_sodium-sys
**2.**
error: failed to run custom build command for `rust_sodium-sys v0.10.3`
process didn't exit successfully: `D:\Users\xxx\Documents\...\target\debug\build\rust_sodium-sys-7d1ff43ff00924a4\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=RUST_SODIUM_LIB_DIR
cargo:rerun-if-env-changed=RUST_SODIUM_USE_PKG_CONFIG
cargo:rerun-if-env-changed=RUST_SODIUM_SHARED

--- stderr
thread 'main' panicked at '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!   unwrap! called on Result::Err                                              !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
C:\Users\xxx\.cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\rust_sodium-sys-0.10.3\build.rs:77,20 in build_script_build

Err(Os { code: -2146893008, kind: Other, message: "The specified data could not be decrypted." })

', C:\Users\xxx\.cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\unwrap-1.2.1\src\lib.rs:67:25
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**3.**
--- stderr
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"f15f96f8999dfa37ae579007d798ba70f6c3015fbfa3b897e9eb037a8df8dfde"`,
 right: `"0580d54f57594a7cb493607cec6e7045369fb67d43623491523781e901589948"`:

Downloaded libsodium file failed hash check.

', C:\Users\xxx\.cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\rust_sodium-sys-0.10.3\build.rs:88:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by S-Coyle** [comment] 2019-02-19 14:32
@czyczk Thanks for reporting this. I've been unable to reproduce today on a Windows 10 machine, plus I've ran our Windows CI which is passing fine. I discussed with some other team members who believe that this could have been caused by a temporary download issue around the time which you were building.
Could you try again and let me know if the issue is resolved for you?

**Comment by czyczk** [comment] 2019-02-20 05:35
> issue

No, it's been around here for several weeks and I believe it's a download issue. I wonder if there's a manual "download and place it somewhere" solution to this.

**Comment by Fraser999** [comment] 2019-02-20 10:26
@czyczk There is such a solution documented [here](https://github.com/maidsafe/rust_sodium#to-use-your-own-copy-of-libsodium).

If you go to https://download.libsodium.org/libsodium/releases and choose either libsodium-1.0.16-msvc.zip (for use with stable-msvc) or libsodium-1.0.16-mingw.tar.gz (for use with stable-gnu) and unpack these, they should contain prebuilt libraries.

Now, when you run `cargo`, just ensure you have an environment variable `RUST_SODIUM_LIB_DIR` set to the path of this unpacked libsodium folder, and it should favour your local copy and avoid trying to download a fresh copy of libsodium.

We're still looking into resolving this issue in a different way btw, but for now this should allow you to work around the problem.

**Comment by Fraser999** [comment] 2019-05-01 12:02
[This PR](https://github.com/maidsafe/rust_sodium/pull/107) should hopefully help.  It adds a fallback URL for the tarballs when the official location is unavailable.  This still allows using your own copy along with `RUST_SODIUM_LIB_DIR` if you prefer.

**Closed by Fraser999** 2019-05-01 12:02 UTC
