### ISSUE TITLE
Review contributor agreement

### ISSUE THREAD

**Issue by infinity0** [maidsafe/crust#631] opened 2016-03-26 16:58 UTC
Hi, I have a few questions about your contributor agreement. Before I go into these however, you should read various arguments [[1]](http://ebb.org/bkuhn/blog/2014/06/09/do-not-need-cla.html) [[2]](https://opensource.com/law/11/7/trouble-harmony-part-1) on why this sort of agreement doesn't actually give your company any extra protection and only costs you more administrative overhead.

Specifically now, there are two issues that worry me about this agreement. 

(a) You assert that I've agreed to it simply by submitting a pull request or some other trivial action that people do all the time on the internet without these sorts of conditions attached. (It's even more trivial than clicking "I agree" that most people do without thinking.) I therefore have to question both the ethical reasonableness of this assertion, as well as how legally enforceable it is.

(b) In the text "Any contribution we make available under any license will also be made available under a suitable [FOSS license]", the condition "we make available under any license" sounds a bit dodgy. It implies that you get all the benefits (that this agreement gives you) *even if* you reject my PR, or if you don't release it (but use it privately and internally), or if you release it under no license. The whole point of my contribution would be for the FOSS product, so this condition is disconcerting.

**Comment by dirvine** [comment] 2016-03-26 18:37
I think these worries are quite personal really. Specifically (b), if a PR is made (I am not sure how having a PR rejected comes into it) then it is part of the GPL code base, but this project may release also under another license to third parties. I do not think it would be possible to prevent the GPL-3.0 always being available etc. So a bit unclear here of the issue. 
For (a) I need to look closer at the agreement (lawyers etc. were involved in the creation of this so will check with them perhaps).  The terms are also on every file in the repo in the header. I am not sure either on enforceability of agree buttons/ acceptance criteria, but 100% the intention here is to remove hassle for people. So I suppose you can have scanned signed agreements (again how enforceable etc.). 

For me the main issue is this is all GPL-3.0 at least and can never be anything other than that as is, however MaidSafe may license to third parties if appropriate. Also may be licensed as GPL only or another FOSS licence. There are issues whichever way it goes here and the priority is to ensure freedom via GPL and also moving forward. 

Ultimately it would be nice to have an answer that will satisfy everyone, but since the early 90's I have never seen such a thing. I don't this this is too far away as is, but of course always looking at improvements. Be good to take these points into the next time we look over licensing, which is important, but also has it's place (is any license really enforceable worldwide etc.)

Again cheers for input and there are some huge threads on the forums about licensing etc. (as you can imagine the debates rage for months and 000#s of posts)./

**Comment by infinity0** [comment] 2016-03-27 11:09
Understood, "always GPL-3 but perhaps we might license other terms to others [*]" is good and fine for FOSS projects. Thanks for stating that more clearly! My issue was more with the wording, which at the moment says "If P then [FOSS]", which isn't the same as [*]. It would be good to clear that up.

Regarding a rejected PR, this is a combination of (a) and (b) together. If the mere act of submitting a pull *request* implies I've agreed to your terms, then these terms apply even if you later reject the request. Addressing (a) and (b) will address this automatically, I was just pointing out a strange consequence of the wording.

**Comment by dirvine** [comment] 2016-03-27 12:21
Ah yes both these points are good and well made. We can certainly clear the wording up and ensure, only accepted pull requests fall under these conditions. Thanks again, clarity is always much better and this will certainly aid that. 

Nice

**Comment by NickLambert** [comment] 2016-03-28 09:40
Thanks for the comments @infinity0 . I agree that we should make it more clear that we will make any and all contribution available under GPL3, something like: "Any contribution we
make available under any license will also be made available under GPL V3."

Regards rejected PRs. I can't imagine a situation where we would reject a PR and then need to use the code internally, if it was a useful PR we would want to incorporate it, however, to make the wording more comfortable can I suggest that we make a statement along the lines of 'MaidSafe has no rights to  intellectual property from rejected pull requests'?

**Comment by infinity0** [comment] 2016-03-28 17:14
Hey,

> something like: "Any contribution we make available [..]"

Did you forget to edit this? (The text you quoted is exactly what's in the current agreement, with the "Any X [which] Y will be Z" conditional clause.) Based on what @dirvine said in the first post, I think it would be clearer to state "Your contribution will be released under GPL-3; however MaidSafe also reserves the right to re-license it under a different license."

On rejected PRs, it could be simpler to state near the front of the agreement that "this agreement only comes into effect for accepted contributions". Then you don't need to mention rejected pull requests specifically.

**Comment by NickLambert** [comment] 2016-03-29 05:57
No, the current agreement states: 'Any contribution we
make available under any license will also be made available under a suitable FSF (Free Software
Foundation) or OSI (Open Source Initiative) approved license.' - I was just making it clear that it was going to be released under the GPL. 

Anyway, I appreciate the suggestions and we will get these changes rolled out across all the libs. Thanks again for your input, much appreciated!

**Comment by burdges** [comment] 2016-03-30 11:58
Just two general thoughts not so specific to maidsafe or crust : 

There should be an effort to lobby GitHub to make big scary legal stuff appear when you fork or send pull requests to projects with CLAs. 

As many CLAs were designed for the iOS situation, we need GPLv3 variants adapted to these App stores with built in CLAs that say basically : 

> The anyone / the project reserves has right to distribute this program through channels whose
> policies conflict with the GPL, such as App stores, subject to the party placing this software
> under the distributors license must must themselves incur the distributors obligations under
> the GPLv3.  To enforce this, this party must : 
> 1.  not grant the distribution the right to modify the software, 
> 2.  must not agree to automatic license modifications by the distributor, 
> 3.  must publish the source code for the used by the distributor, and 
> 4.  must provide reproducible build instructions for reproducing that exact version from the source.

It'd need a framework for updates similar to the GPL's "or later" clause that let the license creator, like the FSF or EFF, adapt to legal changes by Apple, etc., including possibly pulling thousands of applications off the store if Apple caused a problem for the reproducible build requirement.

Apologies if that's off topic here, but just something that came to mind.  :)

**Comment by vinipsmaker** [comment] 2016-03-30 14:06
> It'd need a framework for updates similar to the GPL's "or later" clause that let the license creator, like the FSF or EFF, adapt to legal changes by Apple

I write code for MaidSafe, but my opinion does **NOT** reflect MaidSafe opinion.

And my opinion... ignore Apple.
=P

(I'm sure somebody else from the team will give you a proper answer instead a shitty answer like mine)

**Comment by ustulation** [comment] 2016-06-18 14:50
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.

**Closed by ustulation** 2016-06-18 14:50 UTC
