### ISSUE TITLE
Examples and benchmarks don't run properly on Windows

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/crust#448] opened 2015-12-15 10:43 UTC
Just now, `cargo bench`  hangs while waiting for one service to connect to the other.

The simple_receiver example should connect automatically to an instance of the simple_sender example on the same machine, but it doesn't.

Finally, the simple_benchmark example panics since it's also unable to create a connection.

I guess all these are related to the same issue, but if not we'll need to add separate issues for each.

**Comment by canndrew** [comment] 2015-12-16 11:00
PR for this here: https://github.com/maidsafe/crust/pull/449

**Comment by canndrew** [comment] 2015-12-16 11:11
`cargo bench` isn't hanging for me. It does take a long time to run the `send_random_data` example though (about 5 minutes).

**Comment by canndrew** [comment] 2015-12-16 11:16
Nor does `simple_benchmark` panic for me. Which is weird because this couldn't be related to the `simple_sender`/`simple_receiver` fix.

**Comment by vinipsmaker** [comment] 2015-12-23 06:39
I cannot reproduce the problem in crust master. Gonna close it. Reopen if problem persists.

**Comment by Fraser999** [comment] 2015-12-23 07:54
The simple_sender/simple_receiver examples work OK now, but I still see the benchmark hanging on Windows (left running for > 1 hr) and the simple_benchmark example panics on Windows:
```
F:\MaidSafe\Rust\SuperProject\Crust>cargo run --example simple_benchmark
     Running `target\debug\examples\simple_benchmark.exe`
thread '<main>' panicked at 'Could not connect', examples/simple_benchmark.rs:71
Process didn't exit successfully: `target\debug\examples\simple_benchmark.exe` (exit code: 101)
```

**Comment by madadam** [comment] 2015-12-23 09:29
I think #442 is also related, but needs more work.

**Comment by vinipsmaker** [comment] 2015-12-28 21:09
> I think #442 is also related, but needs more work.

If this is true, then you guys should test again, as `rust-utp` is a tad more stable/reliable after `temp_utp` `0.7.0`. Just test crust `master` to verify.

Also, #442 was surpassed by #454.

**Comment by ustulation** [comment] 2016-06-18 14:45
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.

**Closed by ustulation** 2016-06-18 14:45 UTC
Labels: bug
