### ISSUE TITLE
Failing of connection establishment and missing messages on rust-utp socket test

### ISSUE THREAD

**Issue by maqi** [maidsafe/crust#439] opened 2015-12-02 10:20 UTC
As detailed described in the Rust-UTP PR https://github.com/maidsafe/rust-utp/pull/8

the test proves a failing rate at around : 0.005% when socket without timeout and 0.25% when socket with timeout.

according to the work of Crust PR https://github.com/maidsafe/crust/pull/437 , the test proves the crust level failing rate is around the same as the rust-utp when socket with timeout.

**Comment by vinipsmaker** [comment] 2015-12-02 19:37
I'm suspecting this is being caused by the congestion control algorithm (and the changes brought by the `timeout` branch). I'm going to investigate it in detail.

**Comment by vinipsmaker** [comment] 2015-12-04 17:23
I based my work on top of @maqi's `test_network_utp` [branch](https://github.com/maqi/crust/tree/b6f4af3819740b7c1d39ea30d3a5ab69f7133cfe).

After some attempts, debugging hours, observations and so on, I'm suspecting the problem is on the logic of the network. I believe the problem is on the congestion control algorithm from rust-utp. Missing packets make uTP unreliable. uTP isn't working properly under unreliable connections (which is exactly where UDP is supposed to be used). On the tests done, it was observed that the use of custom user timeout -- which is a feature used by crust to make concurrent reads/writes possible -- would increase the failure/hang rate.

My newest try was to change [`CHECK_FOR_NEW_WRITES_INTERVAL_MS`](https://github.com/maqi/crust/blob/b6f4af3819740b7c1d39ea30d3a5ab69f7133cfe/src/utp_wrapper.rs#L9) to support my claim/suspicion. Making the check more "granular" would increase the chance to not be reading when the packet was sent, which would cause a "lost packet". The "lost packet" is exactly the reason why I believe the test is failing.

Under the usual `50i64`, the rates I got from my machine were:

 ok | err
--- | ----
  6 |  15

When I changed the value to `200i64`, the stats were:

 ok | err
--- | ----
 11 |  10

With my suspicion confirmed (actually, I'd need to run more tests, but they take too long to complete and I already have something to change and test to see if the problem goes away), the next step is to study the congestion control algorithm of rust-utp/uTP and propose a solution to make it more reliable (and maybe give better guarantees on connection timed out). Until a definitive solution is implemented, crust could change the `CHECK_FOR_NEW_WRITES_INTERVAL_MS` value to decrease the rate failure and use ping/pong messages to detect connection loss itself.

Also, we could implement solution `#2` from https://github.com/meqif/rust-utp/issues/4#issue-88255908, which would make the design more reliable.

**Comment by vinipsmaker** [comment] 2015-12-16 14:08
So, I found out that [one PR of ours](https://github.com/meqif/rust-utp/pull/10) broke [µTP LEDBAT](http://www.bittorrent.org/beps/bep_0029.html).

Previously rust-utp would do a [read without a timeout](https://github.com/meqif/rust-utp/blob/0edb5cac3e2c7eb1bf22a63a6c522b652c727f24/src/socket.rs#L408) and would block until this timeout would be reached. So the algorithm was coded in such a way that, when [the timeout was reached](https://github.com/meqif/rust-utp/blob/0edb5cac3e2c7eb1bf22a63a6c522b652c727f24/src/socket.rs#L411-L415), [it'd resend the packet](https://github.com/meqif/rust-utp/blob/0edb5cac3e2c7eb1bf22a63a6c522b652c727f24/src/socket.rs#L489) at the correct time, as specified per LEDBAT. And one of the properties from LEDBAT is that it'd "back off" and slowdown exactly when the network usage is high, which is exactly what we're doing the expose the failure. Also, [the number of retries](https://github.com/meqif/rust-utp/blob/0edb5cac3e2c7eb1bf22a63a6c522b652c727f24/src/socket.rs#L398) would be reached way sooner with small timeouts.

So, my idea to fix the problem is to refactor the code in such a way that we'd compute the passed time ourselves. This means storing the "time point" the last packet was resent (instead of relying on the wrong assumption that enough-time/the-right-amount-of-time has passed on the line following) and moving lines around such that if we're just coming back after a **user** timeout happened, we'll only do a read (and nothing else!) to wait for the packet for more time.

**Comment by vinipsmaker** [comment] 2015-12-24 09:32
Kind of my changes are ready for some time already, but when I try to test against `test_network_utp` from modified (with changes for `utp_wrapper` reverted) #442, no messages are received at all (actual error being `thread 'Service::listen' panicked at 'Error { repr: Custom(Custom { kind: InvalidData, error: StringError("Failed to decode CBOR") }) }', src/state.rs:165` and `src/state.rs:165` being `trans.receiver.receive_handshake().unwrap()`).

I've been debugging what's wrong during this time. Actually I somehow might have broken the `connect` function from rust-utp (which calls `recv`, which is the function I needed to change).

**Comment by vinipsmaker** [comment] 2015-12-28 10:09
> I've been debugging what's wrong during this time. Actually I somehow might have broken the `connect` function from rust-utp (which calls `recv`, which is the function I needed to change).

It should be fixed now with the latest version of the `set-read-timeout` patch:

- https://github.com/meqif/rust-utp/pull/10
- https://github.com/maidsafe/rust-utp/pull/9

Upstream project's CI will timeout, but if you let the test run a little longer, tests will pass.

**Comment by vinipsmaker** [comment] 2015-12-28 19:03
It's merged on `master` now. I'll create a proper PR with the Windows build fix that was suggested earlier among our core devs and then:

1. Update the network test.
2. Confirm the hanging issue.
3. Find an alternative fix that doesn't break current behaviour/usage-patterns.

**Comment by vinipsmaker** [comment] 2015-12-28 21:05
Gonna close this issue as [the rust-utp reliability problem was solved](https://github.com/maidsafe/crust/pull/454). We should open another issue to track Windows hanging issue.

**Closed** 2015-12-28 21:05 UTC
