### ISSUE TITLE
Resolve GNU issue

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/crust#1054] opened 2018-10-26 10:42 UTC

**Comment by S-Coyle** [comment] 2018-10-30 11:49
@nbaksalyar @jacderida am I right in saying this has been resolved?

**Comment by nbaksalyar** [comment] 2018-10-31 10:54
Yes, it's been resolved by implementing the automated AppVeyor build.
And this is actually a duplicate of #1024.

**Closed by nbaksalyar** 2018-10-31 10:54 UTC
Labels: Back-end, bug
